SET IDENTITY_INSERT shop.dbo.Collection ON;
INSERT INTO shop.dbo.Collection (CollectionID, Title, Gender)VALUES (1, N'Summer Men', N'Men');
INSERT INTO shop.dbo.Collection (CollectionID, Title, Gender)VALUES (2, N'Summer Woman', N'Woman');
INSERT INTO shop.dbo.Collection (CollectionID, Title, Gender)VALUES (3, N'Summer Children', N'Child');
SET IDENTITY_INSERT shop.dbo.Collection OFF;
SET IDENTITY_INSERT shop.dbo.Customer ON;
INSERT INTO shop.dbo.Customer (CustomerID, FirstName, LastName, Gender, AddressLine1, AddressLine2, PostalCode, Country, Phone, Email, NIF)VALUES (1, N'Carlos', N'Leite', N'Men', N'Rua ali da cena', N'Rua ali da outra cena', N'4610-154', N'PT', N'936291996', N'8200383@estg.ipp.pt', N'214523778');
SET IDENTITY_INSERT shop.dbo.Customer OFF;
SET IDENTITY_INSERT shop.dbo.Product ON;
INSERT INTO shop.dbo.Product (ProductID,CollectionID, Title, Description)VALUES (1,1, N'Ibiza Tee', N'Oversized Tee with the Logo on the front');
SET IDENTITY_INSERT shop.dbo.Product ON;
INSERT INTO shop.dbo.Product (ProductID,CollectionID, Title, Description)VALUES (2, 1, N'Cloud Tee', N'Oversized Tee with a sentence in the back');
SET IDENTITY_INSERT shop.dbo.Product OFF;
SET IDENTITY_INSERT shop.dbo.Product OFF;
SET IDENTITY_INSERT shop.dbo.Seller ON;
INSERT INTO shop.dbo.Seller (SellerID,FirstName, LastName, NIF, ShiftStart, ShiftEnd)VALUES (1,N'Sergio', N'Felix', N'261994905', N'10:00:00', N'16:00:00');
SET IDENTITY_INSERT shop.dbo.Seller OFF;
SET IDENTITY_INSERT shop.dbo.Sale ON;
INSERT INTO shop.dbo.Sale (SaleID,CustomerID,SellerID)VALUES (1, 1, 1);
SET IDENTITY_INSERT shop.dbo.Sale OFF;
SET IDENTITY_INSERT shop.dbo.ProductLine ON;
INSERT INTO shop.dbo.ProductLine (ProductLineID, ProductID, Color, Size, WarehouseQuantity, StandQuantity, Stand, Price)VALUES (1,1, N'Off White', N'L', 30, 5, 2, 43);
SET IDENTITY_INSERT shop.dbo.ProductLine ON;
INSERT INTO shop.dbo.ProductLine (ProductLineID, ProductID, Color, Size, WarehouseQuantity, StandQuantity, Stand, Price)VALUES (2, 2, N'Brown', N'L', 30, 8, 2, 41);
SET IDENTITY_INSERT shop.dbo.ProductLine OFF;
SET IDENTITY_INSERT shop.dbo.ProductLine OFF;
SET IDENTITY_INSERT shop.dbo.SaleLine ON;
INSERT INTO shop.dbo.SaleLine (SaleLineID,SaleID, ProductLineID, Quantity)VALUES (1, 1, 1, 2);
INSERT INTO shop.dbo.SaleLine (SaleLineID,SaleID, ProductLineID, Quantity) VALUES (2,1,2,4);
SET IDENTITY_INSERT shop.dbo.SaleLine OFF;
INSERT INTO shop.dbo.Defect (CreatedBy,ProductLineID) VALUES (1, 1);
